/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fleet;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.WindowConstants;

/**
 *
 * @author Theresa
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        try
{
   // UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
       UIManager.put("nimbusBase", new Color(119,199,240));
      UIManager.put("nimbusBlueGrey",new Color(119,199,240));
     UIManager.put("control",Color.WHITE);
       UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
}
 catch(Exception e) {}
        
        Dimension m = Toolkit.getDefaultToolkit().getScreenSize();
     
             setLocation(m.width/3,m.height/5);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        desk = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        RegisterVehicle = new javax.swing.JMenuItem();
        ViewAllVehicle = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        RegisterDriver = new javax.swing.JMenuItem();
        ViewAll = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Logs = new javax.swing.JMenuItem();
        allLogs = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Accident = new javax.swing.JMenuItem();
        AllReport = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        registeruser = new javax.swing.JMenuItem();

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DASHBOARD");
        setResizable(false);

        javax.swing.GroupLayout deskLayout = new javax.swing.GroupLayout(desk);
        desk.setLayout(deskLayout);
        deskLayout.setHorizontalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        deskLayout.setVerticalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(desk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(desk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Welcome, User");

        logoutButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logoutButton.setText("LOGOUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(logoutButton))
                .addGap(18, 18, 18))
        );

        jMenu1.setText("Vehicle");

        RegisterVehicle.setText("Register Vehicle");
        RegisterVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterVehicleActionPerformed(evt);
            }
        });
        jMenu1.add(RegisterVehicle);

        ViewAllVehicle.setText("Available Vehicles");
        ViewAllVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAllVehicleActionPerformed(evt);
            }
        });
        jMenu1.add(ViewAllVehicle);

        jMenuItem1.setText("Vehicle Requests");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Driver");

        RegisterDriver.setText("Register Driver");
        RegisterDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterDriverActionPerformed(evt);
            }
        });
        jMenu2.add(RegisterDriver);

        ViewAll.setText("View All ");
        ViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAllActionPerformed(evt);
            }
        });
        jMenu2.add(ViewAll);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Logs");

        Logs.setText("Vehicle maintenance");
        Logs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogsActionPerformed(evt);
            }
        });
        jMenu3.add(Logs);

        allLogs.setText("View all logs");
        allLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allLogsActionPerformed(evt);
            }
        });
        jMenu3.add(allLogs);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Records");

        Accident.setText("Report an accident");
        Accident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccidentActionPerformed(evt);
            }
        });
        jMenu4.add(Accident);

        AllReport.setText("View All records");
        AllReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllReportActionPerformed(evt);
            }
        });
        jMenu4.add(AllReport);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Users");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        registeruser.setText("Register user");
        registeruser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registeruserActionPerformed(evt);
            }
        });
        jMenu5.add(registeruser);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterVehicleActionPerformed
        // TODO add your handling code here:
        RegisterVehicle rv= new RegisterVehicle();
        desk.add(rv);
        rv.setVisible(true);
    }//GEN-LAST:event_RegisterVehicleActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Successful", "Logout successful", JOptionPane.INFORMATION_MESSAGE);
        LoginDialog login= new LoginDialog();
        login.setVisible(true);
        this.setVisible(false);
        login.setDefaultCloseOperation(JDialog.EXIT_ON_CLOSE);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void ViewAllVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAllVehicleActionPerformed
        // TODO add your handling code here:
         EditVehicle rv= new EditVehicle();
        desk.add(rv);
        rv.setVisible(true);
    }//GEN-LAST:event_ViewAllVehicleActionPerformed

    private void RegisterDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterDriverActionPerformed
        // TODO add your handling code here:
        RegisterDriver rd= new RegisterDriver();
        desk.add(rd);
        rd.setVisible(true);
    }//GEN-LAST:event_RegisterDriverActionPerformed

    private void ViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAllActionPerformed
        // TODO add your handling code here:
        EditDriver ed= new EditDriver();
        desk.add(ed);
        ed.setVisible(true);
    }//GEN-LAST:event_ViewAllActionPerformed

    private void LogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogsActionPerformed
        // TODO add your handling code here:
        VehicleMaintenanceForm vm = new VehicleMaintenanceForm();
        desk.add(vm);
        vm.setVisible(true);
    }//GEN-LAST:event_LogsActionPerformed

    private void AccidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccidentActionPerformed
        // TODO add your handling code here:
        AccidentReport ac= new AccidentReport();
        desk.add(ac);
        ac.setVisible(true);
    }//GEN-LAST:event_AccidentActionPerformed

    private void AllReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllReportActionPerformed
        // TODO add your handling code here:
        AllReport ar= new AllReport();
        desk.add(ar);
        ar.setVisible(true);
    }//GEN-LAST:event_AllReportActionPerformed

    private void allLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allLogsActionPerformed
        // TODO add your handling code here:
        LogMaintenance lm= new LogMaintenance();
        desk.add(lm);
        lm.setVisible(true);
    }//GEN-LAST:event_allLogsActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void registeruserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registeruserActionPerformed
        // TODO add your handling code here:
        RegisterUser ru= new RegisterUser();
        desk.add(ru);
        ru.setVisible(true);
    }//GEN-LAST:event_registeruserActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Request r= new Request();
        desk.add(r);
        r.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Accident;
    private javax.swing.JMenuItem AllReport;
    private javax.swing.JMenuItem Logs;
    private javax.swing.JMenuItem RegisterDriver;
    private javax.swing.JMenuItem RegisterVehicle;
    private javax.swing.JMenuItem ViewAll;
    private javax.swing.JMenuItem ViewAllVehicle;
    private javax.swing.JMenuItem allLogs;
    private javax.swing.JDesktopPane desk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JMenuItem registeruser;
    // End of variables declaration//GEN-END:variables
}
