/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fleet;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Theresa
 */
public class EditDriver extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditDriver
     */
    public EditDriver() {
        
        initComponents();
        
           try
{
   // UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
       UIManager.put("nimbusBase", new Color(119,199,240));
      UIManager.put("nimbusBlueGrey",new Color(119,199,240));
 //    UIManager.put("control",Color.WHITE);
       UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
}
 catch(Exception e) {}
        
           DefaultTableModel m = (DefaultTableModel) tab.getModel();
        String query = "select name,address,age, state from drivers";
        String[] cols = {"name","address","age","state"};
        ArrayList<ArrayList<String>> drivers=new Connection().getAllMultipleColumnData(query, cols);


        if(drivers.size()>0)
        {
            for(int i=0; i <drivers.get(0).size(); i++)
            {
              
                 String name = drivers.get(0).get(i);
                 String address = drivers.get(1).get(i);
                 String age = drivers.get(2).get(i);
                 String state=  drivers.get(3).get(i);
                
                

                     m.addRow(new Object[]{i+1,name,address,age,state});

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        deleteButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("ALL DRIVERS");

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S/N", "Name", "Address", "Age", "State of origin"
            }
        ));
        tab.setToolTipText("ALL DRIVERS");
        jScrollPane1.setViewportView(tab);

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
         DefaultTableModel m = (DefaultTableModel)tab.getModel();
          int row = tab.getSelectedRow();
          String name="";
          boolean flag=false;
           try{
          name= m.getValueAt(row, 1).toString();
          int resp= JOptionPane.showConfirmDialog(this,"Are you sure you want to delete driver "+name, "Confirm Delete", JOptionPane.YES_NO_OPTION);
         if(resp==0)
          flag = true;

          }catch(Exception ex){}

          if(flag)
          {
               String query = "";
                    if(name.isEmpty())
                        JOptionPane.showMessageDialog(this,"Requester not retreived!","Error",JOptionPane.ERROR_MESSAGE);
                    else
                    {
                       
                        {
                          query = "delete from drivers where name='"+name+"'";

                            boolean deleted = new Connection().executeCommand("delete", query);
                               
                            if(deleted)
                            { m.removeRow(row);
                                JOptionPane.showMessageDialog(this, "Driver Deleted!", "Success", JOptionPane.INFORMATION_MESSAGE);
                            }
                            else
                                 JOptionPane.showMessageDialog(this, "Driver not deleted!", "Error", JOptionPane.ERROR_MESSAGE);

                        }
                    }
          }
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables
}
